pipeline {
    agent any
    environment {
	NGINX_ROOT = '/var/lib/jenkins/www'
	APP_PATH = '/var/lib/jenkins/www/phpcart'
	APP_UPL = '/var/lib/jenkins/www/phpcart/admin/uploads'
}
    stages {
        stage('Prepare') {
            steps {
		sh 'if [ ! -d  ${NGINX_ROOT} ]; then mkdir ${NGINX_ROOT}; fi'
		sh 'cd ${NGINX_ROOT} && git clone https://github.com/tomich/phpcart.git || true'
                sh 'git checkout'
                sh 'cd ${APP_PATH} && chmod -R 777 ${APP_UPL}'
            }
        }
        stage('start') {
            steps {
                sh 'cd /var/lib/jenkins/workspace/DevOpAppTest/docker-files && docker-compose build && docker-compose up -d'
            }
        }
        stage('Test') {
            steps {
		sh 'sleep 3 && if [ $(curl -s -o /dev/null -w "%{http_code}\n" http://localhost:8081/) != "200" ]; then exit 1; fi'
            }
        }
    }
}
