pipeline {
    agent any
    environment {
	NGINX_ROOT = '/var/lib/jenkins/www'
	APP_PATH = '/var/lib/jenkins/www/phpcart'
	APP_UPL = '/var/lib/jenkins/www/phpcart/admin/uploads'
}
    stages {
        stage('Prepare') {
            steps {
		if(!fileExists(env.NGINX_ROOT)) {
			sh 'mkdir ${NGINX_ROOT}'
		 }
		sh 'cd ${NGINX_ROOT}' 
                sh 'git clone https://github.com/tomich/phpcart.git || true'
                sh 'git checkout'
                sh 'cd ${APP_PATH}'
                sh 'chmod -R 777 ${APP_UPL}'
            }
        }
        stage('start') {
            steps {
                sh 'cd /vagrant/docker-files'
                sh 'docker-compose up -d'
            }
        }
        stage('Test') {
            steps {
                sh 'echo "test ok :P"'
            }
        }
    }
}
