#Nombre de la imagen Docker que usamos, obtenida a travez del docker hub. Para mas información de configuracion, ver docker-compose en mismo directorio.
FROM webdevops/php-nginx:ubuntu-18.04

# Instalacion de paquetes complementarios
RUN apt-get update && apt-get install -y mysql-client php-mysql
